POST http://localhost:8000/api/blogs
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhbmlzaCIsImlkIjoiNjk1NDNiNDBjNDUxMDVmNGQxODIxMzQxIiwiaWF0IjoxNzY3MTI4NzM1LCJleHAiOjE3NjcxMzIzMzV9.KgTf_Z-GnTeKDFeLzjKm75-WTcPuSqfbyfLFkLAIWuM

{
    "title": "Blog 2",
    "author": "Tanish",
    "url": "https://www.google.com"
}


###

GET http://localhost:8000/api/blogs
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OTUxMzZjMDIwMjEyYTA2N2JiMWY0MzEiLCJpYXQiOjE3NjcwOTM4MDN9.fTY8F6-AUIL3oBvHK191Z910UyFnAAem5JXn4tpnPkg